language: python
#python:
# - "3.6"
virtualenv:
  system_site_packages: false
# command to install dependencies
services:
  - postgresql
before_script:
  - psql -c 'create database api_test;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install gunicorn
# command to run tests
script:
  - pytest
deploy:
  provider: heroku
  api_key: 6ba74b86-f408-47fc-a7a3-5479ac8ff54d
  on: production
